database:
  host: localhost
  port: 5432
  user: root
  password: databasefyp
  name: imdb
  data_path: /var/lib/postgresql/12/main
  pg_version: 12
  cluster_name: main

tuning:
  method: HEBO
  iterations: 100
  sample_num: 5
  config: knob_config/knob_config.json
  
benchmark:
  type: olap
  name: job
  path: ./olap_workloads
  workload_execution: logs/performance/workload_execution.log
  performance_record_path: logs/performance_record
  benchbase_jar: /home/benchbase/target/benchbase-postgres/benchbase.jar

surrogate:
  model_path: /home/E2ETune-AI4DB/surrogate/cost_model.pkl
