SELECT SUM(LO_EXTENDEDPRICE * LO_DISCOUNT) AS revenue 
FROM lineorder_flat 
WHERE LO_ORDERDATE >= 19930101 AND LO_ORDERDATE <= 19931231 
  AND LO_DISCOUNT BETWEEN 1 AND 3 AND LO_QUANTITY < 25;

SELECT SUM(LO_EXTENDEDPRICE * LO_DISCOUNT) AS revenue 
FROM lineorder_flat 
WHERE LO_ORDERDATE >= 19940101 AND LO_ORDERDATE <= 19940131 
  AND LO_DISCOUNT BETWEEN 4 AND 6 AND LO_QUANTITY BETWEEN 26 AND 35;

SELECT SUM(LO_EXTENDEDPRICE * LO_DISCOUNT) AS revenue 
FROM lineorder_flat 
WHERE (LO_ORDERDATE / 10000) = 1994 
  AND (LO_ORDERDATE / 100) % 100 = 1 -- Example for January
  AND LO_DISCOUNT BETWEEN 5 AND 7 AND LO_QUANTITY BETWEEN 26 AND 35;

-- Q2.1
SELECT SUM(LO_REVENUE), (LO_ORDERDATE / 10000) AS YEAR, P_BRAND 
FROM lineorder_flat 
WHERE P_CATEGORY = 'MFGR#12' AND S_REGION = 'AMERICA' 
GROUP BY YEAR, P_BRAND ORDER BY YEAR, P_BRAND;

-- Q2.2
SELECT SUM(LO_REVENUE), (LO_ORDERDATE / 10000) AS YEAR, P_BRAND 
FROM lineorder_flat 
WHERE P_BRAND BETWEEN 'MFGR#2221' AND 'MFGR#2228' AND S_REGION = 'ASIA' 
GROUP BY YEAR, P_BRAND ORDER BY YEAR, P_BRAND;

-- Q2.3
SELECT SUM(LO_REVENUE), (LO_ORDERDATE / 10000) AS YEAR, P_BRAND 
FROM lineorder_flat 
WHERE P_BRAND = 'MFGR#2239' AND S_REGION = 'EUROPE' 
GROUP BY YEAR, P_BRAND ORDER BY YEAR, P_BRAND;

-- Q3.1
SELECT C_NATION, S_NATION, (LO_ORDERDATE / 10000) AS YEAR, SUM(LO_REVENUE) AS revenue 
FROM lineorder_flat 
WHERE C_REGION = 'ASIA' AND S_REGION = 'ASIA' 
  AND LO_ORDERDATE >= 19920101 AND LO_ORDERDATE <= 19971231 
GROUP BY YEAR, C_NATION, S_NATION ORDER BY YEAR ASC, revenue DESC;

-- Q3.2
SELECT C_CITY, S_CITY, (LO_ORDERDATE / 10000) AS YEAR, SUM(LO_REVENUE) AS revenue 
FROM lineorder_flat 
WHERE C_NATION = 'UNITED STATES' AND S_NATION = 'UNITED STATES' 
  AND LO_ORDERDATE >= 19920101 AND LO_ORDERDATE <= 19971231 
GROUP BY YEAR, C_CITY, S_CITY ORDER BY YEAR ASC, revenue DESC;

-- Q3.3
SELECT C_CITY, S_CITY, (LO_ORDERDATE / 10000) AS YEAR, SUM(LO_REVENUE) AS revenue 
FROM lineorder_flat 
WHERE (C_CITY = 'UNITED KI1' OR C_CITY = 'UNITED KI5') 
  AND (S_CITY = 'UNITED KI1' OR S_CITY = 'UNITED KI5') 
  AND LO_ORDERDATE >= 19920101 AND LO_ORDERDATE <= 19971231 
GROUP BY YEAR, C_CITY, S_CITY ORDER BY YEAR ASC, revenue DESC;

-- Q3.4
SELECT C_CITY, S_CITY, (LO_ORDERDATE / 10000) AS YEAR, SUM(LO_REVENUE) AS revenue 
FROM lineorder_flat 
WHERE (C_CITY = 'UNITED KI1' OR C_CITY = 'UNITED KI5') 
  AND (S_CITY = 'UNITED KI1' OR S_CITY = 'UNITED KI5') 
  AND (LO_ORDERDATE / 100) % 100 = 12 
  AND LO_ORDERDATE >= 19970101 AND LO_ORDERDATE <= 19971231 
GROUP BY YEAR, C_CITY, S_CITY ORDER BY YEAR ASC, revenue DESC;

-- Q4.1
SELECT (LO_ORDERDATE / 10000) AS YEAR, C_NATION, SUM(LO_REVENUE - LO_SUPPLYCOST) AS profit 
FROM lineorder_flat 
WHERE C_REGION = 'AMERICA' AND S_REGION = 'AMERICA' 
  AND (P_MFGR = 'MFGR#1' OR P_MFGR = 'MFGR#2') 
GROUP BY YEAR, C_NATION ORDER BY YEAR, C_NATION;

-- Q4.2
SELECT (LO_ORDERDATE / 10000) AS YEAR, S_NATION, P_CATEGORY, SUM(LO_REVENUE - LO_SUPPLYCOST) AS profit 
FROM lineorder_flat 
WHERE C_REGION = 'AMERICA' AND S_REGION = 'AMERICA' 
  AND (LO_ORDERDATE / 10000 = 1997 OR LO_ORDERDATE / 10000 = 1998) 
  AND (P_MFGR = 'MFGR#1' OR P_MFGR = 'MFGR#2') 
GROUP BY YEAR, S_NATION, P_CATEGORY ORDER BY YEAR, S_NATION, P_CATEGORY;

-- Q4.3
SELECT (LO_ORDERDATE / 10000) AS YEAR, S_CITY, P_BRAND, SUM(LO_REVENUE - LO_SUPPLYCOST) AS profit 
FROM lineorder_flat 
WHERE S_NATION = 'UNITED STATES' 
  AND (LO_ORDERDATE / 10000 = 1997 OR LO_ORDERDATE / 10000 = 1998) 
  AND P_CATEGORY = 'MFGR#14' 
GROUP BY YEAR, S_CITY, P_BRAND ORDER BY YEAR, S_CITY, P_BRAND;
